### ISSUE TITLE
PostgresSQLEnum arrays error

### ISSUE THREAD

**Issue by gperdomor** [vapor/fluent-postgres-driver#96] opened 2018-09-10 16:03 UTC
I have this enum
```swift
enum Permission: String, PostgreSQLEnum, PostgreSQLMigration {
    ...
    case asset_create = "asset:create"
    case asset_delete = "asset:delete"
    case asset_read = "asset:read"
    case asset_update = "asset:update"
    ...
}
```

this Entity:

```swift
final class Role: PostgreSQLUUIDModel, Migration, Content {
    static var entity = "roles"
    
    var id: UUID?
    var name: String
    var permissions: [Permission]

    init(name: String, permissions: [Permission]) {
        self.name = name
        self.permissions = permissions
    }
}
```

this migration:

```swift
struct RoleDemo: Migration {
    typealias Database = PostgreSQLDatabase
    
    static func prepare(on connection: PostgreSQLConnection) -> Future<Void> {
        let role = Role(
            name: "Demo",
            permissions: [.asset_create, .item_create]
        )
        
        return role.save(on: connection).transform(to: ())
    }
    
    static func revert(on connection: PostgreSQLConnection) -> Future<Void> {
        return .done(on: connection)
    }
}
```

And finally... This error:

```
Thread 1: Fatal error: Error raised at top level: ⚠️ PostgreSQL Error: column "permissions" is of type permission[] but expression is of type text[]
- id: PostgreSQLError.server.error.transformAssignedExpr

These suggestions could address the issue: 
- You will need to rewrite or cast the expression.
```

**Comment by grundoon** [comment] 2018-09-10 17:01
Have you added `Permission` as a migration in your `configure.swift`, prior to its use within the `Role` migration?

```swift
var migrations = MigrationConfig()
migrations.add(migration: Permission.self, database: .psql)
migrations.add(model: Role.self, database: .psql)
// ...
services.register(migrations)```

**Comment by docterd** [comment] 2018-09-23 09:47
@gperdomor Did you find a workaround for this issue?

**Comment by gperdomor** [comment] 2018-09-24 11:38
@docterd no :(

**Comment by MihaelIsaev** [comment] 2019-01-19 21:02
Same here
```swift
enum UserRole: String, PostgreSQLEnum, PostgreSQLMigration {
    case admin, manager, promoter, hipster
}
```
trying to create a `User`
```swift
final class User: Content {
    var id: UUID?
    var phone: String
    var roles: [UserRole]
    var createdAt, updatedAt, deletedAt: Date?
}
```
but getting error
```bash
⚠️ PostgreSQL Error: column "roles" is of type userrole[] but expression is of type text[]
```

**Comment by tanner0101** [comment] 2019-01-29 03:22
Hmm I'll have to look into this. Enums were never tested inside of arrays, so not a huge surprise it doesn't work. 

As a workaround, you should be able to use just `enum UserRole: String { ... }` and do the enum validation in Swift instead of the DB.

**Comment by Janoz94** [comment] 2019-03-22 13:09
Any workaround or maybe is there already solution for it?

**Comment by tanner0101** [comment] 2019-04-02 19:35
@Janoz94 to clarify my idea for a workaround, you could store the enum values as `[String]`, and then have a mutable computed property on the model that converts to / from `[MyEnum]`. No solution has been found yet, but I'll make sure it gets fixed by the next major release at the latest.

**Comment by mcritz** [comment] 2019-09-08 03:16
I have this exact same issue. Happy to see it’s got a healthy discussion. I’d love to either see this feature work as intended or have a best practices documentation so other devs don’t step on the same landmine.

**Comment by tanner0101** [comment] 2020-03-06 04:15
This is fixed in Fluent 4. The workarounds mentioned here are the best option for Fluent 3.

**Closed by tanner0101** 2020-03-06 04:15 UTC
Labels: bug
